# Copyright 2024 OmniSafe Team. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

defaults:
  # seed for random number generator
  seed: 0
  # training configurations
  train_cfgs:
    # device to use for training, options: cpu, cuda, cuda:0, cuda:0,1, etc.
    device: cuda:0
    # number of threads for torch
    torch_threads: 128
    # number of vectorized environments
    vector_env_nums: 1
    # number of parallel agent, similar to a3c
    parallel: 1
    # number of training epochs
    num_epochs: 101
    # number of evaluate episodes
    eval_episodes: 0
    raw_policy_episodes: 10
  # algorithm configurations
  algo_cfgs:
    # number of steps to update the policy
    steps_per_epoch: 6000
    # number of steps per sample
    update_cycle: 1
    # number of iterations to update the policy
    update_iters: 1
    # The size of replay buffer
    size: 1000000
    # The size of batch
    batch_size: 256
    # normalize reward
    reward_normalize: False
    # normalize cost
    cost_normalize: False
    # normalize observation
    obs_normalize: False
    # max gradient norm
    max_grad_norm: 40
    # use critic norm
    use_critic_norm: False
    # critic norm coefficient
    critic_norm_coeff: 0.001
    # The soft update coefficient
    polyak: 0.005
    # The discount factor of GAE
    gamma: 0.99
    # Actor perdorm random action before `start_learning_steps` steps
    start_learning_steps: 10000
    # The delay step of policy update
    policy_delay: 2
    # The exploration noise
    exploration_noise: 2.0
    # The value of alpha
    alpha: 0.2
    # Whether to use auto alpha
    auto_alpha: False
    # use cost
    use_cost: False
  # logger configurations
  logger_cfgs:
    # use wandb for logging
    use_wandb: True
    # wandb project name
    wandb_project: omnisafe
    # use tensorboard for logging
    use_tensorboard: True
    # save model frequency
    save_model_freq: 10
    # save logger path
    log_dir: "./runs"
    # save model path
    window_lens: 6
  # model configurations
  model_cfgs:
    # weight initialization mode
    weight_initialization_mode: "kaiming_uniform"
    # actor type
    actor_type: gaussian_sac
    # linear learning rate decay
    linear_lr_decay: False
    # Configuration of Actor network
    actor:
      # Size of hidden layers
      hidden_sizes: [64, 64]
      # Activation function
      activation: relu
      # The learning rate of Actor network
      lr: 0.0003
    # Configuration of Critic network
    critic:
      # The number of critic networks
      num_critics: 2
      # Size of hidden layers
      hidden_sizes: [256, 256]
      # Activation function
      activation: relu
      # The learning rate of Critic network
      lr: 0.0003
  transition_model_cfgs:
    type: "GatedTransitionModel"
    n_ensemble: 5
    n_elites: 5
    frozen: False
    train:
      batch_size: 256
      weight_decay: 7.5e-05
      lr: 0.001
      mul_std: 0
  lyapunov:
    ell_coef: 1.0
    barrier_coef: 1
  opt_s:
    temperature:
      max: 0.03
      min: 0.03
    filter:
      top_k: 10000
      pool: False
    n_steps: 1
    method: "MALA"
    lr: 0.01
    batch_size: 10000
    extend_region: 0.0
    barrier_coef: 0.0
    L_neg_coef: 1
    resample: False
    n_proj_iters: 10
    precond: False
  opt_h:
    weight_decay: 0.0001
    lr: 0.0003
    lambda_2: "norm"
    locals: {}
    n_iters: 500000
  crabs:
    obj:
      eps: 0.01
      neg_coef: 1.0
  n_pretrain_s_iters: 1
  task: "train_policy"
